name: Test nix deploy workflow

on:
  workflow_dispatch:
    inputs:
      hosts:
        description: 'Comma separated hostnames or tags (ex: @desktops) to deploy'
        required: true
        type: string


jobs:

  print-inputs_and_context:
    runs-on: ubuntu-latest
    steps:
      - name: Print the hosts
        run: echo "The hosts are ${{ inputs.hosts }}"
      - name: write to file
        run: echo "Test does this work $GITHUB_WORKSPACE" > ${{ github.workspace }}/testfile
      - name: write SSH Config File
        run: |
          echo "Host *
                  IdentityFile $GITHUB_WORKSPACE/testfile
                " >> ${{ github.workspace }}/ssh_config
      - name: cat file
        run: cat testfile
      - name: cat configfile
        run: cat ${{ github.workspace }}/ssh_config
      - name: cat file another way
        run: cat ${{ github.workspace }}/testfile
      - name: Print the context
        run: echo "The full event context ${{ toJSON(github.event) }}"
